-- Stage 20: atomic, user-owned import for the CSV generated by HireFlow.

create function public.import_applications_csv(p_rows jsonb)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_user_id uuid := (select auth.uid());
  v_row jsonb;
  v_company_id uuid;
  v_application_id uuid;
  v_technology_id uuid;
  v_company_name text;
  v_job_title text;
  v_status text;
  v_work_mode text;
  v_employment_type text;
  v_location text;
  v_source text;
  v_job_url text;
  v_currency text;
  v_applied_at date;
  v_salary_min numeric(14, 2);
  v_salary_max numeric(14, 2);
  v_technology_name text;
  v_inserted integer;
  v_imported integer := 0;
  v_skipped integer := 0;
  v_companies_created integer := 0;
  v_technologies_linked integer := 0;
begin
  if v_user_id is null then
    raise exception using
      errcode = '42501',
      message = 'Authentication required';
  end if;

  if jsonb_typeof(p_rows) is distinct from 'array'
    or jsonb_array_length(p_rows) not between 1 and 200 then
    raise exception using
      errcode = '22023',
      message = 'Import must contain between 1 and 200 rows';
  end if;

  -- Serialize imports from the same account so duplicate detection stays stable.
  perform pg_advisory_xact_lock(hashtextextended(v_user_id::text, 0));

  for v_row in select value from jsonb_array_elements(p_rows)
  loop
    if jsonb_typeof(v_row) is distinct from 'object' then
      raise exception using errcode = '22023', message = 'Invalid import row';
    end if;

    if jsonb_typeof(v_row -> 'companyName') is distinct from 'string'
      or jsonb_typeof(v_row -> 'jobTitle') is distinct from 'string'
      or jsonb_typeof(v_row -> 'status') is distinct from 'string'
      or jsonb_typeof(v_row -> 'currency') is distinct from 'string'
      or jsonb_typeof(v_row -> 'workMode') not in ('string', 'null')
      or jsonb_typeof(v_row -> 'employmentType') not in ('string', 'null')
      or jsonb_typeof(v_row -> 'location') not in ('string', 'null')
      or jsonb_typeof(v_row -> 'source') not in ('string', 'null')
      or jsonb_typeof(v_row -> 'jobUrl') not in ('string', 'null')
      or jsonb_typeof(v_row -> 'appliedAt') not in ('string', 'null') then
      raise exception using errcode = '22023', message = 'Invalid import field type';
    end if;

    v_company_name := regexp_replace(
      btrim(v_row ->> 'companyName'),
      '[[:space:]]+',
      ' ',
      'g'
    );
    v_job_title := btrim(v_row ->> 'jobTitle');
    v_status := v_row ->> 'status';
    v_work_mode := v_row ->> 'workMode';
    v_employment_type := v_row ->> 'employmentType';
    v_location := nullif(btrim(v_row ->> 'location'), '');
    v_source := nullif(btrim(v_row ->> 'source'), '');
    v_job_url := nullif(btrim(v_row ->> 'jobUrl'), '');
    v_currency := v_row ->> 'currency';

    if v_company_name is null
      or char_length(v_company_name) not between 1 and 160
      or v_job_title is null
      or char_length(v_job_title) not between 1 and 180 then
      raise exception using errcode = '22023', message = 'Invalid company or job title';
    end if;

    if v_status is null or v_status <> all (array[
      'saved', 'applied', 'screening', 'hr_interview',
      'technical_interview', 'technical_challenge', 'final_interview',
      'offer', 'hired', 'rejected', 'withdrawn'
    ]) then
      raise exception using errcode = '22023', message = 'Invalid application status';
    end if;

    if v_work_mode is not null
      and v_work_mode <> all (array['remote', 'hybrid', 'onsite']) then
      raise exception using errcode = '22023', message = 'Invalid work mode';
    end if;

    if v_employment_type is not null
      and v_employment_type <> all (array[
        'clt', 'pj', 'internship', 'freelance', 'temporary', 'other'
      ]) then
      raise exception using errcode = '22023', message = 'Invalid employment type';
    end if;

    if char_length(coalesce(v_location, '')) > 160
      or char_length(coalesce(v_source, '')) > 120
      or char_length(coalesce(v_job_url, '')) > 2048
      or (v_job_url is not null and v_job_url !~* '^https?://') then
      raise exception using errcode = '22023', message = 'Invalid optional application field';
    end if;

    if v_currency is null or v_currency <> all (array['BRL', 'USD', 'EUR']) then
      raise exception using errcode = '22023', message = 'Invalid currency';
    end if;

    if jsonb_typeof(v_row -> 'salaryMin') not in ('number', 'null')
      or jsonb_typeof(v_row -> 'salaryMax') not in ('number', 'null') then
      raise exception using errcode = '22023', message = 'Invalid salary';
    end if;

    v_salary_min := (v_row ->> 'salaryMin')::numeric;
    v_salary_max := (v_row ->> 'salaryMax')::numeric;
    if coalesce(v_salary_min, 0) < 0
      or coalesce(v_salary_max, 0) < 0
      or v_salary_min > 999999999999.99
      or v_salary_max > 999999999999.99
      or (v_salary_min is not null and v_salary_max is not null and v_salary_max < v_salary_min) then
      raise exception using errcode = '22023', message = 'Invalid salary range';
    end if;

    begin
      v_applied_at := (v_row ->> 'appliedAt')::date;
    exception
      when invalid_datetime_format or datetime_field_overflow then
        raise exception using errcode = '22023', message = 'Invalid application date';
    end;

    if jsonb_typeof(v_row -> 'technologies') is distinct from 'array'
      or jsonb_array_length(v_row -> 'technologies') > 20 then
      raise exception using errcode = '22023', message = 'Invalid technologies';
    end if;

    if exists (
      select 1
      from jsonb_array_elements(v_row -> 'technologies') as technology(value)
      where jsonb_typeof(technology.value) is distinct from 'string'
    ) then
      raise exception using errcode = '22023', message = 'Invalid technology type';
    end if;

    select companies.id
      into v_company_id
      from public.companies
      where companies.user_id = v_user_id
        and lower(companies.name) = lower(v_company_name)
      order by companies.created_at, companies.id
      limit 1;

    if v_company_id is null then
      insert into public.companies (user_id, name)
      values (v_user_id, v_company_name)
      returning id into v_company_id;
      v_companies_created := v_companies_created + 1;
    end if;

    if exists (
      select 1
      from public.applications
      where applications.user_id = v_user_id
        and applications.company_id = v_company_id
        and lower(applications.job_title) = lower(v_job_title)
        and applications.applied_at is not distinct from v_applied_at
    ) then
      v_skipped := v_skipped + 1;
      continue;
    end if;

    insert into public.applications (
      user_id,
      company_id,
      job_title,
      job_url,
      location,
      work_mode,
      employment_type,
      salary_min,
      salary_max,
      currency,
      applied_at,
      source,
      status
    )
    values (
      v_user_id,
      v_company_id,
      v_job_title,
      v_job_url,
      v_location,
      v_work_mode,
      v_employment_type,
      v_salary_min,
      v_salary_max,
      v_currency,
      v_applied_at,
      v_source,
      v_status::public.application_status
    )
    returning id into v_application_id;

    for v_technology_name in
      select distinct regexp_replace(btrim(value), '[[:space:]]+', ' ', 'g')
      from jsonb_array_elements_text(v_row -> 'technologies')
    loop
      if char_length(v_technology_name) not between 1 and 60 then
        raise exception using errcode = '22023', message = 'Invalid technology name';
      end if;

      insert into public.technologies (user_id, name)
      values (v_user_id, v_technology_name)
      on conflict (user_id, normalized_name) do nothing;

      select technologies.id
        into v_technology_id
        from public.technologies
        where technologies.user_id = v_user_id
          and technologies.normalized_name = lower(v_technology_name);

      insert into public.application_technologies (
        application_id,
        technology_id,
        user_id
      )
      values (v_application_id, v_technology_id, v_user_id)
      on conflict do nothing;

      get diagnostics v_inserted = row_count;
      v_technologies_linked := v_technologies_linked + v_inserted;
    end loop;

    v_imported := v_imported + 1;
  end loop;

  return jsonb_build_object(
    'imported', v_imported,
    'skipped', v_skipped,
    'companiesCreated', v_companies_created,
    'technologiesLinked', v_technologies_linked
  );
end;
$$;

revoke all on function public.import_applications_csv(jsonb)
from public, anon, authenticated;
grant execute on function public.import_applications_csv(jsonb) to authenticated;

comment on function public.import_applications_csv(jsonb) is
  'Atomically imports validated HireFlow CSV rows for auth.uid(), under RLS.';
